@DecisionAddress = http://localhost:5296


###
GET {{DecisionAddress}}/api/schedule/daily/optimal?day=2025-12-01
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/greedy?day=2025-12-01
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/local_search?day=2025-12-01
Accept: application/json

### 1. NOVO: Comparação Multi-Crane (Algoritmo Configurável)
# Opções para algorithm: 'greedy', 'local_search', 'optimal'
GET {{DecisionAddress}}/api/schedule/daily/multi-crane-comparison?day=2025-12-01&algorithm=local_search
Accept: application/json