@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor black
}

title Customer Use Case Diagram

left to right direction

rectangle "System Actors                       " as actors {
    actor "Shipping Agent Representative" as SAR
}


rectangle "Customer App"  as usecases{
    usecase "Creat/Submit Vessel Visit Notifications" as CSVVN
    usecase "Change/Complete Vessel Visit Notifications" as CCVVN
    usecase "View Status of Vessel Visit Notifications" as VSoVVN

    SAR ---> CSVVN
    SAR ---> CCVVN
    SAR ----> VSoVVN

}



@enduml