@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true

skinparam rectangle{
    BorderColor black
}

title Main Use Case Diagram

left to right direction

rectangle "System Actors                       " as actors {
    actor "Port Authority Officer" as PAO
    actor "Logistics Operator" as LO
}


rectangle "Backend" as usecases{
    usecase "Create/Update Vessel types" as CUVT
    usecase "Create/Update Vessel records" as CUVR
    usecase "Create/Update Docks" as CUD
    usecase "Create/Update Storages Areas" as CUSA
    usecase "Register Shipping Agent Org" as RSAO
    usecase "Create/Update/Deactivate SAR" as RSAR
    usecase "Approve/Reject Vessel Visit Notifications" as ARVVN

    PAO -=-> CUVT
    PAO -=-> CUVR
    PAO -=-> CUD
    PAO -=-> CUSA
    PAO -=-> RSAO
    PAO -=-> RSAR
    PAO -=-> ARVVN

    usecase "Register/Manage Operating Staff" as RMOS
    usecase "Register/Manage Physical Resources" as RMPR
    usecase "Register/Manage Qualifications" as RMQ

    LO --> RMOS
    LO --> RMPR
    LO --> RMQ
}

@enduml