###
POST http://localhost:3000/api/complementary-task-categories
Content-Type: application/json

{
  "code": "CTC003",
  "name": "Onboard Security Check",
  "description": "Security inspection performed onboard the vessel",
  "category": "Safety and Securityw",
  "defaultDuration": 60
}